# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AzureRmPipelineConnection'
    subscriptionId: '7c2d65a9-a683-4fe6-86ba-3dcfcfe78ec1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'h-armTutorial'
    location: 'West US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/hila-m/armSamples/main/azuredeploy.json'
    overrideParameters: ''
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'